# Generated by Django 2.2.7 on 2020-05-27 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='train',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('train_no', models.CharField(blank=True, max_length=50)),
                ('train_from', models.CharField(blank=True, max_length=50)),
                ('dep_time', models.CharField(blank=True, max_length=50)),
                ('train_to', models.CharField(blank=True, max_length=50)),
                ('arr_time', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_sits', models.IntegerField(blank=True)),
                ('booking_class', models.CharField(blank=True, max_length=10)),
                ('ph_no', models.IntegerField(blank=True)),
                ('name1', models.CharField(blank=True, max_length=100)),
                ('nationality1', models.CharField(blank=True, max_length=50)),
                ('gender1', models.CharField(blank=True, max_length=50)),
                ('age1', models.IntegerField(blank=True)),
                ('name2', models.CharField(blank=True, max_length=100)),
                ('nationality2', models.CharField(blank=True, max_length=50)),
                ('gender2', models.CharField(blank=True, max_length=50)),
                ('age2', models.IntegerField(blank=True)),
                ('name3', models.CharField(blank=True, max_length=100)),
                ('nationality3', models.CharField(blank=True, max_length=50)),
                ('gender3', models.CharField(blank=True, max_length=50)),
                ('age3', models.IntegerField(blank=True)),
                ('name4', models.CharField(blank=True, max_length=100)),
                ('nationality4', models.CharField(blank=True, max_length=50)),
                ('gender4', models.CharField(blank=True, max_length=50)),
                ('age4', models.IntegerField(blank=True)),
                ('name5', models.CharField(blank=True, max_length=100)),
                ('nationality5', models.CharField(blank=True, max_length=50)),
                ('gender5', models.CharField(blank=True, max_length=50)),
                ('age5', models.IntegerField(blank=True)),
                ('name6', models.CharField(blank=True, max_length=100)),
                ('nationality6', models.CharField(blank=True, max_length=50)),
                ('gender6', models.CharField(blank=True, max_length=50)),
                ('age6', models.IntegerField(blank=True)),
                ('t_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='train.train')),
            ],
        ),
    ]
