# Generated by Django 2.2.7 on 2020-05-27 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='age2',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
