# Generated by Django 2.2.7 on 2020-05-27 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0004_auto_20200527_2002'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='booking_sits',
            new_name='booking_seats',
        ),
    ]
